//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen1
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_informe
    {
        public int id_detalle { get; set; }
        public int id_informe { get; set; }
        public string observacion_usuario { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        public virtual informe informe { get; set; }
    }
}
