//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen1
{
    using System;
    using System.Collections.Generic;
    
    public partial class informe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public informe()
        {
            this.detalle_informe = new HashSet<detalle_informe>();
        }
    
        public int id_informe { get; set; }
        public string rut_usuario { get; set; }
        public string rut_stakeholder { get; set; }
        public string diagnostico_usuario { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_informe> detalle_informe { get; set; }
        public virtual stakeholder stakeholder { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
