//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_MatasanosEntities : DbContext
    {
        public bd_MatasanosEntities()
            : base("name=bd_MatasanosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agenda> agenda { get; set; }
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<detalle_informe> detalle_informe { get; set; }
        public virtual DbSet<especialidad> especialidad { get; set; }
        public virtual DbSet<especialista> especialista { get; set; }
        public virtual DbSet<examen> examen { get; set; }
        public virtual DbSet<informe> informe { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<stakeholder> stakeholder { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
