//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laboratorio7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autor_Libro
    {
        public int Id_Autor_Libro { get; set; }
        public int Id_autor_fk { get; set; }
        public int Id_libro_fk { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
